# Generated by Django 2.1 on 2019-01-12 06:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='friend',
            field=models.ManyToManyField(related_name='fried', to=settings.AUTH_USER_MODEL, verbose_name='Друг'),
        ),
    ]
