# Generated by Django 2.1 on 2019-01-12 06:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190112_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='friend',
            field=models.ManyToManyField(blank=True, related_name='fried', to=settings.AUTH_USER_MODEL, verbose_name='Друг'),
        ),
    ]
