# Generated by Django 2.1 on 2019-01-12 07:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20190112_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='friend',
            field=models.ManyToManyField(blank=True, related_name='friend', to=settings.AUTH_USER_MODEL, verbose_name='friend'),
        ),
    ]
